params = {
    'batch_size': 16,
    'grad_clip': 10.,
    'nlayers': 3,
    'learning_rate': 0.0005,
    'num_epochs': 5,
    'validation_frequency': 500,
    'anneal_frequency': 2500,
    'stopping_criterion': True,
    'logging_frequency': 5,
    'nhidden'   :   64,
    'char_dim'  :   10,
    'char_filter_size': 50,
    'char_filter_width': 5,
    'dropout'   :   0.2,
    'word2vec'  :   'glove',
    'train_emb' :   1,
    'use_feat'  :   1,
    'max_chains': 50,
    'num_relations': 2,
    'relation_dims': 32,
    'num_unknown_types': 100,
    'max_word_len': 15,
    'vocab_size': 100000,
    'num_characters': 500,
    'max_doc_len': 2200,
}
