params = {
    'batch_size': 64,
    'grad_clip': 10.,
    'learning_rate': 0.0005,
    'num_epochs': 5,
    'validation_frequency': 500,
    'anneal_frequency': 1,
    'stopping_criterion': True,
    'ensemble': 3,
    'logging_frequency': 10,
    'nhidden'   :   256,
    'char_dim'  :   0,
    'dropout'   :   0.2,
    'word2vec'  :   'glove',
    'train_emb' :   1,
    'use_feat'  :   0,
    'max_chains': 15,
    'num_relations': 2,
    'relation_dims': 128,
    'cloze': True,
}
